/** Bilingual dictionary for the client-facing verification pages (Spanish default). */
export const V_DICT = {
  es: {
    title: "Verificación de información",
    dobPrompt: "Para proteger su información, ingrese la fecha de nacimiento del titular:",
    dobLabel: "Fecha de nacimiento",
    continue: "Continuar",
    wrongDob: "La fecha no coincide. Intente de nuevo.",
    locked: "Este enlace fue bloqueado por seguridad. Su agente se comunicará con usted.",
    expired: "Este enlace ya no está disponible. Comuníquese con su agente para recibir uno nuevo.",
    used: "Ya recibimos su respuesta. ¡Gracias!",
    confirmTitle: "Confirme su información",
    confirmIntro: "Revise que su información siga igual:",
    name: "Titular",
    address: "Dirección",
    members: "Miembros del hogar",
    income: "Ingreso anual registrado",
    plan: "Plan actual",
    allSame: "✅ Todo sigue igual",
    somethingChanged: "✏️ Algo cambió",
    changesTitle: "¿Qué cambió?",
    changesIntro: "Complete solo lo que cambió. Deje en blanco lo demás.",
    newIncome: "Nuevo ingreso anual del hogar ($)",
    employment: "Cambios de empleo (quién, dónde trabaja ahora)",
    newAddress: "Nueva dirección",
    street: "Calle y número",
    city: "Ciudad",
    state: "Estado",
    zip: "Código postal",
    contact: "Nuevo teléfono o correo",
    phone: "Teléfono",
    email: "Correo electrónico",
    removeMembers: "Marque a quien YA NO está en el hogar:",
    addMembers: "Personas NUEVAS en el hogar:",
    firstName: "Nombre",
    lastName: "Apellido",
    dob: "Fecha de nacimiento",
    uploadLabel: "Foto de comprobante de ingreso (opcional)",
    consentLabel: "He leído y acepto:",
    submit: "Enviar",
    doneTitle: "¡Listo! Gracias.",
    doneBody: "Su agente revisará la información y se comunicará si necesita algo más.",
    langToggle: "English",
  },
  en: {
    title: "Information verification",
    dobPrompt: "To protect your information, enter the primary member's date of birth:",
    dobLabel: "Date of birth",
    continue: "Continue",
    wrongDob: "That date doesn't match. Try again.",
    locked: "This link was locked for security. Your agent will contact you.",
    expired: "This link is no longer available. Contact your agent for a new one.",
    used: "We already received your response. Thank you!",
    confirmTitle: "Confirm your information",
    confirmIntro: "Check that your information is still correct:",
    name: "Primary member",
    address: "Address",
    members: "Household members",
    income: "Annual income on file",
    plan: "Current plan",
    allSame: "✅ Everything is the same",
    somethingChanged: "✏️ Something changed",
    changesTitle: "What changed?",
    changesIntro: "Fill in only what changed. Leave the rest blank.",
    newIncome: "New annual household income ($)",
    employment: "Employment changes (who, where they work now)",
    newAddress: "New address",
    street: "Street address",
    city: "City",
    state: "State",
    zip: "ZIP code",
    contact: "New phone or email",
    phone: "Phone",
    email: "Email",
    removeMembers: "Check anyone who is NO LONGER in the household:",
    addMembers: "NEW people in the household:",
    firstName: "First name",
    lastName: "Last name",
    dob: "Date of birth",
    uploadLabel: "Photo of income proof (optional)",
    consentLabel: "I have read and agree:",
    submit: "Submit",
    doneTitle: "Done! Thank you.",
    doneBody: "Your agent will review the information and contact you if anything else is needed.",
    langToggle: "Español",
  },
} as const;

export type VLang = keyof typeof V_DICT;
export type VDict = { [K in keyof (typeof V_DICT)["es"]]: string };

export function pickLang(preferred: string | null | undefined, override?: string): VLang {
  if (override === "en" || override === "es") return override;
  return preferred === "en" ? "en" : "es";
}
